
#Область includr_etrn_base_CommonModule_ОпределениеМодуляКода
#КонецОбласти // includr_etrn_base_CommonModule_ОпределениеМодуляКода

#Область includr_etrn_base_CommonModule_ЗначениеМетаданных
#КонецОбласти // includr_etrn_base_CommonModule_ЗначениеМетаданных

#Область includr_etrn_base_CommonModule_Метаданные
#КонецОбласти // includr_etrn_base_CommonModule_Метаданные

