
#Область includr_etrn_src_vo2_CommonModule_ВыполнениеФункцииНаСервере //&НаСервере
#КонецОбласти // includr_etrn_src_vo2_CommonModule_ВыполнениеФункцииНаСервере

#Область include_etrn_src_vo2_CommonModule_ОпределениеМодуляКода
#КонецОбласти // include_etrn_src_vo2_CommonModule_ОпределениеМодуляКода

#Область include_etrn_src_vo2_CommonModule_ОпределениеМодуляКодаКлиент
#КонецОбласти // include_etrn_src_vo2_CommonModule_ОпределениеМодуляКодаКлиент

#Область include_etrn_src_vo2_CommonModule_ЗначениеМетаданных
#КонецОбласти // include_etrn_src_vo2_CommonModule_ЗначениеМетаданных

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ФормаОбъект //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ФормаОбъект

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСвязаннымиТаблицами //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСвязаннымиТаблицами

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_Общие //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_Общие

#Область include_etrn_src_vo2_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСтроками
#КонецОбласти // include_etrn_src_vo2_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСтроками

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ЮрЛицаИнтерфейс
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ЮрЛицаИнтерфейс

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_РаботаСЮрЛицами
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_РаботаСЮрЛицами

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСЮрЛицами //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСЮрЛицами

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_КонтактныеДанные //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_КонтактныеДанные

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РолиКонтрагентов //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РолиКонтрагентов

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ОткрытиеФорм
#КонецОбласти // include_etrn_base_CommonModule_Saby_ТНОбщегоНазначенияКлиент_ОткрытиеФорм

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ОбщиеСтруктуры //&НаСервере
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ОбщиеСтруктуры

#Область include_etrn_src_vo2_CommonModule_МетаданныеКлиентСервер // &НаКлиентеНаСервереБезКонтекста
#КонецОбласти // include_etrn_src_vo2_CommonModule_Метаданные

