
#Область include_etrn_src_vo3_CommonModule_ВыполнениеФункцииНаСервере //&НаСервере
#КонецОбласти // include_etrn_src_vo3_CommonModule_ВыполнениеФункцииНаСервере //&НаСервере

#Область include_etrn_src_vo3_CommonModule_ОпределениеМодуляКода
#КонецОбласти // include_etrn_src_vo3_CommonModule_ОпределениеМодуляКода

#Область include_etrn_src_vo3_CommonModule_ОпределениеМодуляКодаКлиент
#КонецОбласти // include_etrn_src_vo3_CommonModule_ОпределениеМодуляКодаКлиент

#Область include_etrn_src_vo3_CommonModule_ЗначениеМетаданных
#КонецОбласти // include_etrn_src_vo3_CommonModule_ЗначениеМетаданных

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_Общие //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_Общие //&НаКлиенте

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ОбщиеСтруктуры //&НаСервере
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ОбщиеСтруктуры //&НаСервере

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_СвойстваЭлементовФормы //&НаСервере
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_СвойстваЭлементовФормы //&НаСервере

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ПредставлениеДанных //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ПредставлениеДанных //&НаКлиенте

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ЮрЛицаИнтерфейс
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ЮрЛицаИнтерфейс

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_РаботаСЮрЛицами
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_РаботаСЮрЛицами

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСЮрЛицами
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСЮрЛицами

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиент_ОткрытиеФорм
#КонецОбласти // include_etrn_base_CommonModule_Saby_ТНОбщегоНазначенияКлиент_ОткрытиеФорм

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ФормаОбъект //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_ФормаОбъект //&НаКлиенте

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_КонтактныеДанные //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_КонтактныеДанные //&НаКлиенте

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РолиКонтрагентов //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РолиКонтрагентов //&НаКлиенте

#Область include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСвязаннымиТаблицами //&НаКлиенте
#КонецОбласти // include_etrn_base_CommonModule_ТНОбщегоНазначенияКлиентСервер_РаботаСоСвязаннымиТаблицами //&НаКлиенте

